name: Broken Workflow

on:
  workflow_dispatch:

jobs:
  broken:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Invalid Syntax
      run: echo "Hello, World!  
